### ISSUE TITLE
`make clean` is overly aggressive; prunes all docker resources on system

### ISSUE THREAD

**Issue by kepae** [ethyca/fidesdemo#13]
### Is your feature request related to a specific problem?

The `make clean` invocation is a bit aggressive; the current clean will execute `docker system prune -a --volumes`, which will clear all resources and volumes in the docker storage-- including those unrelated to `fidesdemo`. The command _does_ require user input to proceed, but given the small amount of data in the postgres DB volume that this demo can generate it seems like a dangerous default clean.

Further, `docker prune` is executed first, before cleaning venv and fides-related artifacts. Cancelling the `docker prune` (like I did) then leaves these artifacts, which are perhaps more important to dispose of for the purpose of the demo.

### Describe the solution you'd like

`make clean` should not prune volumes, and prompt the user to delete them themselves; it's better to leave a dangling volume than delete more than was installed by fidesdemo. (Which may happen with the prune anyways.)
Also, venv and fides-related cleaning should happen first, regardless of whether or the `docker prune` behavior should change. This way, users can opt-out of the `docker-prune` and still have the other files deleted.

In fact, `make reset-db` already calls `docker volume rm fidesdemo_postgres`, which should perhaps be the behavior replicated in `make clean`.

### Describe alternatives you've considered, if any

One way to better target `docker prune` may be to use the `--filter=<key>=<value>` argument, if labels can be set in the docker-compose workflow for all docker resources created for the demo (e.g. containers, networks, volumes).

**Comment by iamkelllly** [comment]
Thank you for this @kepae , we've also addressed this in ethyca/fides#417, we will be implementing something similar with the demo repo as well! Stay tuned!
