### ISSUE TITLE
make install gives error related to fidesctl distribution not available

### ISSUE THREAD

**Issue by waghsac** [ethyca/fidesdemo#15]
### Bug Description

_A description of what the bug is._

#### Steps to Reproduce

I have setup the pre-requisites as required for fidesdemo. 
When I execute the make install command, it gives me the below error while building the environment.

waghsac@WAGHSAC:~/fidesdemo$ make install
Bringing up docker containers...
WARN[0000] Found orphan containers ([fidesdemo-fidesops-1 fidesdemo-redis-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Running 4/4
 ⠿ Container fidesdemo-db-1        Started                                                                                                                             1.2s
 ⠿ Container fidesdemo-fidesctl-1  Started                                                                                                                             2.6s
 ⠿ Container fidesdemo-redis-1     Started                                                                                                                             1.0s
 ⠿ Container fidesdemo-fidesops-1  Started                                                                                                                             1.3s
localhost:5432 - accepting connections
Creating virtual environment ./venv...
Installing project dependencies...
Collecting black>=21.9b0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/2e/ef/a38a2189959246543e60859fb65bd3143129f6d18dfc7bcdd79217f81ca2/black-22.3.0-py3-none-any.whl
Collecting click>=7.0.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4a/a8/0b2ced25639fb20cc1c9784de90a8c25f9504a7f18cd8b5397bd61696d7d/click-8.0.4-py3-none-any.whl
**Collecting fidesctl==1.2.0 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement fidesctl==1.2.0 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for fidesctl==1.2.0 (from -r requirements.txt (line 3))
Makefile:32: recipe for target 'install' failed
make: *** [install] Error 1**

I'm using Ubuntu 18.04 LTS on Windows.

**Comment by waghsac** [comment]
@conceptualshark can you please help?

**Comment by iamkelllly** [comment]
@waghsac thank you for reporting this error!  We want to get this routed to the fidesctl team, can you also provide the version of `make` you're using?

**Comment by waghsac** [comment]
@iamkelllly thanks, will watch. Make version details as below.
waghsac@WAGHSAC:~$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
waghsac@WAGHSAC:~$

**Comment by waghsac** [comment]
@iamkelllly thanks, will watch. Make version details as below.
Make version - GNU Make 4.1.

**Comment by NevilleS** [comment]
That's very curious, because the `fidesctl` version it's looking for is right here: https://pypi.org/project/fidesctl/1.2.0/

The install procedure should create a `venv` and then use the `pip` version from there. Can you share the output of `./venv/bin/pip --version`, e.g.
```
~/git/fidesdemo% ./venv/bin/pip --version
pip 21.3.1 from /Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by ThomasLaPiana** [comment]
can confirm i was able to `pip install fidesctl==1.2.0` and `pip install -r requirements.txt`

**Comment by waghsac** [comment]
@NevilleS 
waghsac@WAGHSAC:~/fidesdemo$ ./venv/bin/pip --version
pip 9.0.1 from /home/waghsac/fidesdemo/venv/lib/python3.6/site-packages (python 3.6)

**Comment by waghsac** [comment]
Tried the new version and got the same error.
waghsac@WAGHSAC:~/fidesdemo$ pip install fidesctl[postgres,aws]==1.6.0
Collecting fidesctl[aws,postgres]==1.6.0
  Could not find a version that satisfies the requirement fidesctl[aws,postgres]==1.6.0 (from versions: )
No matching distribution found for fidesctl[aws,postgres]==1.6.0

**Comment by NevilleS** [comment]
I see- your `pip` version is quite old (2016), I think it's probably suggesting an upgrade? Let me double-check what the command is for that

**Comment by NevilleS** [comment]
OK, you can use `pip install --upgrade pip` to get a more recent release. I'm not 100% sure that's the problem, but it's a good next step

**Comment by waghsac** [comment]
Updated the pip version but same error. Updated the python version as well but its not reflecting somehow.

Creating virtual environment ./venv...
Installing project dependencies using pip version:
**pip 21.3.1 from /home/waghsac/fidesdemo/venv/lib/python3.6/site-packages/pip (python 3.6)**
./venv/bin/pip install -r requirements.txt
Collecting black>=21.9b0
  Using cached black-22.3.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
Collecting click>=7.0.0
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
ERROR: Could not find a version that satisfies the requirement fidesctl[aws,postgres]==1.6.0 (from versions: none)
ERROR: No matching distribution found for fidesctl[aws,postgres]==1.6.0
Makefile:65: recipe for target 'install' failed

**Comment by waghsac** [comment]
Thanks @NevilleS @ThomasLaPiana upgrading the pip and python version worked.
