### ISSUE TITLE
Improve Windows Support

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fidesdemo#18]
### Bug Description

Many of the make targets leverage some handy shell techniques that only work on UNIX systems, but I'd like to get this demo project working smoothly on Windows.

#### Steps to Reproduce

Attempt to run the minimal demo targets on Windows:
1. `make install`
2. `make demo`

### Expected behavior

These commands should run successfully and the demo environment should be fully usable.

**Comment by ThomasLaPiana** [comment]
this is a major reason I ended up going with nox, but I know that'd take more refactoring than you might be looking for

**Comment by NevilleS** [comment]
This likely won't happen - right now this example repo feels over-engineered, and a scaled back version with just a docker-compose file and a README is likely more appropriate, and more platform agnostic 😄
