### ISSUE TITLE
Validate (and update) Fidesdemo for fidesctl 1.8.1

### ISSUE THREAD

**Issue by SteveDMurphy** [ethyca/fidesdemo#19]
### Is your feature request related to a specific problem?

`fidesctl==1.8.1` was released. With that in mind, we should validate the demo workflow as is, and update accordingly.

This issue should focus on just the current functionality, not adding new content

### Describe the solution you'd like

Walk through the `fidesctl` demo portion as is, and ensure no issues are present.

### Describe alternatives you've considered, if any

Also including new content, but that seems like it would distract from the goal of ensuring the fidesdemo is fully functional

### Additional context

https://github.com/ethyca/fides/releases/tag/1.8.1

Acceptance Criteria
- The UI should load on the main branch of the demo

**Comment by mfbrown** [comment]
Let's change this to focus on 1.7.1 which we should release this week.

**Comment by mfbrown** [comment]
Updated to 1.8.1

**Comment by SteveDMurphy** [comment]
@mfbrown this is all spinning up and the UI is visible for both `fidesops` and `fidesctl` - let me know if you'd like to review together as part of acceptance criteria and closure (will open a PR with the changes as well)
